### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by CodeMadUser** [megvii-research/DCLS-SR#4]
作者，你好，请问
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    opt = option.parse(parser.parse_args().opt, is_train=False)
  File "D:\pythonProject\7_4\DCLS-SR-master\DCLS-SR-master\codes\config\DCLS\options.py", line 60, in parse
    config_dir = path.split("/")[-2]
IndexError: list index out of range
这个是为啥？一直不行，还有一个问题就是先验模型放在哪个位置呢？可以详细写下测试过程吗？测试过程不需要数据集吧？感谢

**Comment by Algolzw** [comment]
1. 测试是需要测试集的。你需要下载所需的数据集(Set5、Set14、Urban100、BSD100、Manga109)，然后run:
`python3 codes/scripts/generate_mod_blur_LR_bic.py`
(记得修改参数)

2. 模型位置你可以在config文件中修改，具体参考[codes/config/DCLS/options/setting1/test/test_setting1_x4.yml](codes/config/DCLS/options/setting1/test/test_setting1_x4.yml)

**Comment by CodeMadUser** [comment]
> 1. 测试是需要测试集的。你需要下载所需的数据集(Set5、Set14、Urban100、BSD100、Manga109)，然后run:
>    `python3 codes/scripts/generate_mod_blur_LR_bic.py`
>    (记得修改参数)
> 2. 模型位置你可以在config文件中修改，具体参考[codes/config/DCLS/options/setting1/test/test_setting1_x4.yml](codes/config/DCLS/options/setting1/test/test_setting1_x4.yml)
感谢你回复我。如果我要用自己的图片来测试的化只需要修改数据集的路径，并生成数据集文件就可以使用你训练好的先验模型进行测试了。可以吗？

**Comment by Algolzw** [comment]
> * 测试是需要测试集的。你需要下载所需的数据集(Set5、Set14、Urban100、BSD100、Manga109)，然后run:
>   `python3 codes/scripts/generate_mod_blur_LR_bic.py`
>   (记得修改参数)
> * 模型位置你可以在config文件中修改，具体参考[codes/config/DCLS/options/setting1/test/test_setting1_x4.yml](codes/config/DCLS/options/setting1/test/test_setting1_x4.yml)
>   感谢你回复我。如果我要用自己的图片来测试的化只需要修改数据集的路径，并生成数据集文件就可以使用你训练好的先验模型进行测试了。可以吗？

是的
